"""Initial migrations

Revision ID: aaa1c2e65c64
Revises: 
Create Date: 2026-07-15 14:33:37.098792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa1c2e65c64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('favourite_movies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('group_rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_group_rooms_room_code'), 'group_rooms', ['room_code'], unique=True)
    op.create_index(op.f('ix_group_rooms_room_id'), 'group_rooms', ['room_id'], unique=False)
    op.create_table('preferences',
    sa.Column('pref_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('similar_movies', sa.JSON(), nullable=True),
    sa.Column('preferred_genres', sa.JSON(), nullable=True),
    sa.Column('preferred_cast', sa.JSON(), nullable=True),
    sa.Column('preferred_crew', sa.JSON(), nullable=True),
    sa.Column('runtime_min', sa.Integer(), nullable=True),
    sa.Column('runtime_max', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pref_id')
    )
    op.create_index(op.f('ix_preferences_pref_id'), 'preferences', ['pref_id'], unique=False)
    op.create_table('group_members',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pref_id'], ['preferences.pref_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['group_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members')
    op.drop_index(op.f('ix_preferences_pref_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_group_rooms_room_id'), table_name='group_rooms')
    op.drop_index(op.f('ix_group_rooms_room_code'), table_name='group_rooms')
    op.drop_table('group_rooms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
